from __future__ import annotations

from datetime import datetime, timedelta, timezone


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def build_demo_dataset() -> dict:
    now = utc_now()
    days = lambda value: now - timedelta(days=value)
    hours = lambda value: now - timedelta(hours=value)

    return {
        "collections": [
            {
                "id": "col-001",
                "name": "Governance & Compliance",
                "slug": "governance-compliance",
                "description": "Policies, compliance processes, safety controls, and audit evidence.",
                "color": "emerald",
                "created_at": days(100),
                "updated_at": days(14),
            },
            {
                "id": "col-002",
                "name": "Engineering Standards",
                "slug": "engineering-standards",
                "description": "LLM architecture, API standards, RAG, and technical implementation references.",
                "color": "blue",
                "created_at": days(90),
                "updated_at": days(10),
            },
            {
                "id": "col-003",
                "name": "Operations Playbooks",
                "slug": "operations-playbooks",
                "description": "SOPs and internal workflow documentation for knowledge operations.",
                "color": "amber",
                "created_at": days(80),
                "updated_at": days(3),
            },
        ],
        "sources": [
            {
                "id": "src-001",
                "title": "AI Policy & Governance Guidelines v2.1",
                "source_type": "pdf",
                "mime_type": "application/pdf",
                "file_path": "/sources/ai-policy-governance-v2.1.pdf",
                "uploaded_at": days(96),
                "updated_at": days(96),
                "created_by": "Alice Chen",
                "parse_status": "indexed",
                "ingest_status": "indexed",
                "metadata_json": {"pageCount": 47, "version": "2.1", "department": "Compliance"},
                "checksum": "a3f2b8c1d9e4f6a7b8c9d0e1f2a3b4c5",
                "trust_level": "authoritative",
                "file_size": 2458624,
                "description": "Official AI governance policy covering ethical use, safety standards, and compliance requirements.",
                "tags": ["policy", "governance", "compliance", "ethics", "ai"],
                "collection_id": "col-001",
            },
            {
                "id": "src-002",
                "title": "Technical Standards for LLM Systems v1.0",
                "source_type": "pdf",
                "mime_type": "application/pdf",
                "file_path": "/sources/llm-technical-standards-v1.0.pdf",
                "uploaded_at": days(88),
                "updated_at": days(72),
                "created_by": "Bob Martinez",
                "parse_status": "indexed",
                "ingest_status": "indexed",
                "metadata_json": {"pageCount": 89, "version": "1.0", "department": "Engineering"},
                "checksum": "b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9",
                "trust_level": "authoritative",
                "file_size": 4102912,
                "description": "Technical standards defining API, evaluation, and deployment requirements for LLM systems.",
                "tags": ["technical", "llm", "standards", "engineering"],
                "collection_id": "col-002",
            },
            {
                "id": "src-003",
                "title": "Internal SOP: Document Processing Workflow",
                "source_type": "markdown",
                "mime_type": "text/markdown",
                "file_path": "/sources/sop-document-processing.md",
                "uploaded_at": days(76),
                "updated_at": days(67),
                "created_by": "Carol Nguyen",
                "parse_status": "indexed",
                "ingest_status": "indexed",
                "metadata_json": {"version": "1.2", "department": "Operations"},
                "checksum": "c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0",
                "trust_level": "high",
                "file_size": 98560,
                "description": "Standard operating procedure for ingestion, parsing, chunking, embedding, and QA.",
                "tags": ["sop", "operations", "workflow", "document-processing"],
                "collection_id": "col-003",
            },
            {
                "id": "src-004",
                "title": "API Reference & Integration Guide",
                "source_type": "markdown",
                "mime_type": "text/markdown",
                "file_path": "/sources/api-integration-guide.md",
                "uploaded_at": days(65),
                "updated_at": days(65),
                "created_by": "David Park",
                "parse_status": "extracted",
                "ingest_status": "extracted",
                "metadata_json": {"version": "2.3", "apiVersion": "v2", "endpoints": 42},
                "checksum": "d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1",
                "trust_level": "high",
                "file_size": 187392,
                "description": "Developer guide for integrating with the LLM Wiki platform via REST API.",
                "tags": ["api", "integration", "developer", "reference"],
                "collection_id": "col-002",
            },
            {
                "id": "src-005",
                "title": "Q1 2025 Knowledge Base Update",
                "source_type": "markdown",
                "mime_type": "text/markdown",
                "file_path": "/sources/q1-2025-kb-update.md",
                "uploaded_at": days(47),
                "updated_at": days(47),
                "created_by": "Emma Wilson",
                "parse_status": "indexed",
                "ingest_status": "indexed",
                "metadata_json": {"quarter": "Q1-2025", "topics": ["rag", "safety", "evaluation"]},
                "checksum": "e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2",
                "trust_level": "high",
                "file_size": 134528,
                "description": "Quarterly update covering new RAG architecture patterns and safety evaluation updates.",
                "tags": ["quarterly", "update", "rag", "safety"],
                "collection_id": "col-002",
            },
        ],
        "chunks": [
            {"id": "chunk-001", "source_id": "src-001", "chunk_index": 0, "section_title": "Introduction and Scope", "page_number": 1, "content": "These guidelines apply to all AI systems including LLMs, RAG systems, and automated decision-making tools.", "token_count": 148, "embedding_id": "emb-001", "span_start": 0, "span_end": 412, "created_at": days(96)},
            {"id": "chunk-002", "source_id": "src-001", "chunk_index": 1, "section_title": "Safety Standards for LLM Deployment", "page_number": 8, "content": "Before any LLM is deployed to production, it must pass the Safety Evaluation Framework including fairness, citation, and PII checks.", "token_count": 134, "embedding_id": "emb-002", "span_start": 1200, "span_end": 1850, "created_at": days(96)},
            {"id": "chunk-003", "source_id": "src-002", "chunk_index": 0, "section_title": "LLM Integration Architecture", "page_number": 1, "content": "LLM systems must use a layered architecture separating interface, logic, and data layers.", "token_count": 156, "embedding_id": "emb-003", "span_start": 0, "span_end": 890, "created_at": days(88)},
            {"id": "chunk-004", "source_id": "src-002", "chunk_index": 1, "section_title": "RAG Architecture Standards", "page_number": 24, "content": "RAG systems must implement hybrid retrieval combining dense vector search with BM25 and chunk-level citations.", "token_count": 182, "embedding_id": "emb-004", "span_start": 7200, "span_end": 8100, "created_at": days(88)},
            {"id": "chunk-005", "source_id": "src-003", "chunk_index": 0, "section_title": "Document Ingestion Pipeline", "page_number": 1, "content": "The workflow covers ingestion, parsing, chunking, embedding, and QA with a 512-token sliding window fallback.", "token_count": 210, "embedding_id": "emb-005", "span_start": 0, "span_end": 1450, "created_at": days(76)},
            {"id": "chunk-006", "source_id": "src-003", "chunk_index": 1, "section_title": "Quality Assurance Checkpoints", "page_number": 5, "content": "Chunks failing QA are routed to manual review, which must be completed within 48 hours.", "token_count": 125, "embedding_id": "emb-006", "span_start": 1600, "span_end": 2150, "created_at": days(76)},
            {"id": "chunk-007", "source_id": "src-004", "chunk_index": 0, "section_title": "Authentication and Authorization", "page_number": 1, "content": "All API requests must include a valid Bearer token and role-based authorization is enforced.", "token_count": 138, "embedding_id": "emb-007", "span_start": 0, "span_end": 720, "created_at": days(65)},
            {"id": "chunk-008", "source_id": "src-005", "chunk_index": 0, "section_title": "Q1 RAG Architecture Updates", "page_number": 1, "content": "Parent document retrieval and HyDE improved recall and reduced citation fragmentation.", "token_count": 195, "embedding_id": "emb-008", "span_start": 0, "span_end": 1100, "created_at": days(47)},
        ],
        "entities": [
            {"id": "ent-001", "name": "Retrieval-Augmented Generation", "entity_type": "concept", "description": "Technique that retrieves relevant knowledge before generation.", "aliases": ["RAG"], "normalized_name": "retrieval-augmented generation", "created_at": days(88)},
            {"id": "ent-002", "name": "Knowledge Graph", "entity_type": "concept", "description": "Structured representation of entities and relationships.", "aliases": ["KG"], "normalized_name": "knowledge graph", "created_at": days(88)},
            {"id": "ent-003", "name": "Safety Evaluation Framework", "entity_type": "process", "description": "Evaluation process for AI safety, bias, and privacy.", "aliases": ["SEF"], "normalized_name": "safety evaluation framework", "created_at": days(96)},
            {"id": "ent-004", "name": "Embedding Model", "entity_type": "technology", "description": "Model that converts text into vectors for search.", "aliases": ["embedding"], "normalized_name": "embedding model", "created_at": days(76)},
            {"id": "ent-005", "name": "Prompt Engineering", "entity_type": "concept", "description": "Practice of designing prompts to achieve reliable outputs.", "aliases": [], "normalized_name": "prompt engineering", "created_at": days(65)},
            {"id": "ent-006", "name": "AI Governance", "entity_type": "concept", "description": "Framework for compliant and responsible AI deployment.", "aliases": ["AI policy"], "normalized_name": "ai governance", "created_at": days(96)},
        ],
        "claims": [
            {"id": "clm-001", "source_chunk_id": "chunk-002", "text": "All LLM deployments must pass the Safety Evaluation Framework before production use.", "claim_type": "rule", "confidence_score": 95, "canonical_status": "verified", "review_status": "approved", "extracted_at": days(96), "topic": "safety", "entity_ids": ["ent-003", "ent-006"]},
            {"id": "clm-002", "source_chunk_id": "chunk-002", "text": "Citation accuracy must exceed 90 percent for grounded answers.", "claim_type": "fact", "confidence_score": 92, "canonical_status": "verified", "review_status": "approved", "extracted_at": days(96), "topic": "evaluation", "entity_ids": ["ent-003"]},
            {"id": "clm-003", "source_chunk_id": "chunk-004", "text": "RAG systems must implement hybrid retrieval combining dense vector search with BM25.", "claim_type": "rule", "confidence_score": 88, "canonical_status": "verified", "review_status": "approved", "extracted_at": days(88), "topic": "rag", "entity_ids": ["ent-001", "ent-002"]},
            {"id": "clm-004", "source_chunk_id": "chunk-006", "text": "Chunks failing QA must be reviewed manually within 48 hours.", "claim_type": "rule", "confidence_score": 85, "canonical_status": "verified", "review_status": "pending", "extracted_at": days(76), "topic": "operations", "entity_ids": ["ent-004"]},
            {"id": "clm-005", "source_chunk_id": "chunk-008", "text": "Parent document retrieval reduces citation fragmentation by 34 percent.", "claim_type": "fact", "confidence_score": 78, "canonical_status": "unverified", "review_status": "pending", "extracted_at": days(47), "topic": "rag", "entity_ids": ["ent-001"]},
        ],
        "claim_relations": [
            {"id": "cr-001", "from_claim_id": "clm-003", "from_entity_id": None, "to_claim_id": None, "to_entity_id": "ent-001", "relation_type": "mentions", "confidence_score": 0.94}
        ],
        "pages": [
            {"id": "page-001", "slug": "ai-governance-overview", "title": "AI Governance Overview", "page_type": "summary", "status": "published", "summary": "Overview of the AI governance framework and operational controls.", "content_md": "# AI Governance Overview\n\nThis page summarizes governance and safety requirements for AI systems.", "content_html": None, "current_version": 3, "last_composed_at": days(30), "last_reviewed_at": days(14), "published_at": days(14), "owner": "Alice Chen", "tags": ["governance", "policy"], "parent_page_id": None, "key_facts": ["Safety evaluation is mandatory before production.", "All AI systems require human accountability."], "related_page_ids": ["page-004", "page-006"], "related_entity_ids": ["ent-003", "ent-006"], "collection_id": "col-001"},
            {"id": "page-002", "slug": "llm-integration-standards", "title": "LLM Integration Standards", "page_type": "deep_dive", "status": "published", "summary": "Technical standards for API design, retrieval orchestration, and validation.", "content_md": "# LLM Integration Standards\n\nLayered architecture, validation, and retrieval patterns.", "content_html": None, "current_version": 4, "last_composed_at": days(19), "last_reviewed_at": days(10), "published_at": days(10), "owner": "Bob Martinez", "tags": ["llm", "architecture"], "parent_page_id": None, "key_facts": ["Layered architecture is required.", "Chunk-level citations are required."], "related_page_ids": ["page-003"], "related_entity_ids": ["ent-001", "ent-002"], "collection_id": "col-002"},
            {"id": "page-003", "slug": "rag-architecture", "title": "RAG Architecture", "page_type": "deep_dive", "status": "in_review", "summary": "Architecture patterns for grounded generation and retrieval.", "content_md": "# RAG Architecture\n\nHybrid retrieval, re-ranking, and chunk attribution.", "content_html": None, "current_version": 2, "last_composed_at": days(7), "last_reviewed_at": None, "published_at": None, "owner": "Emma Wilson", "tags": ["rag", "retrieval"], "parent_page_id": None, "key_facts": ["Hybrid retrieval is the default.", "Fallback should avoid hallucination."], "related_page_ids": ["page-002"], "related_entity_ids": ["ent-001", "ent-002"], "collection_id": "col-002"},
            {"id": "page-004", "slug": "document-processing-pipeline", "title": "Document Processing Pipeline", "page_type": "overview", "status": "draft", "summary": "Processing flow from ingestion to embedding and QA.", "content_md": "# Document Processing Pipeline\n\nIngestion, parsing, chunking, embedding, QA.", "content_html": None, "current_version": 1, "last_composed_at": days(3), "last_reviewed_at": None, "published_at": None, "owner": "Carol Nguyen", "tags": ["operations", "pipeline"], "parent_page_id": None, "key_facts": ["512-token sliding window is fallback.", "QA SLA is 48 hours."], "related_page_ids": ["page-001"], "related_entity_ids": ["ent-004"], "collection_id": "col-003"},
            {"id": "page-005", "slug": "api-authentication", "title": "API Authentication", "page_type": "faq", "status": "stale", "summary": "Bearer token and RBAC requirements for API access.", "content_md": "# API Authentication\n\nBearer tokens expire after 3600 seconds.", "content_html": None, "current_version": 2, "last_composed_at": days(50), "last_reviewed_at": days(49), "published_at": days(49), "owner": "David Park", "tags": ["api", "auth"], "parent_page_id": None, "key_facts": ["Bearer token required.", "RBAC is enforced."], "related_page_ids": [], "related_entity_ids": ["ent-005"], "collection_id": "col-002"},
            {"id": "page-006", "slug": "safety-evaluation-framework", "title": "Safety Evaluation Framework", "page_type": "deep_dive", "status": "published", "summary": "Detailed evaluation framework for safety, bias, and privacy.", "content_md": "# Safety Evaluation Framework\n\nBias, citation, hallucination, and PII checks.", "content_html": None, "current_version": 5, "last_composed_at": days(12), "last_reviewed_at": days(8), "published_at": days(8), "owner": "Alice Chen", "tags": ["safety", "evaluation"], "parent_page_id": None, "key_facts": ["Fairness threshold is 85 percent.", "PII detection threshold is 95 percent."], "related_page_ids": ["page-001"], "related_entity_ids": ["ent-003", "ent-006"], "collection_id": "col-001"},
        ],
        "page_versions": [
            {"id": "pv-001", "page_id": "page-001", "version_no": 3, "content_md": "Current governance overview content.", "change_summary": "Refined policy summary", "created_at": days(14), "created_by_agent_or_user": "Alice Chen", "review_status": "approved"},
            {"id": "pv-002", "page_id": "page-002", "version_no": 4, "content_md": "Current LLM standards content.", "change_summary": "Added retrieval section", "created_at": days(10), "created_by_agent_or_user": "Bob Martinez", "review_status": "approved"},
            {"id": "pv-003", "page_id": "page-003", "version_no": 2, "content_md": "Current RAG architecture draft.", "change_summary": "Added HyDE notes", "created_at": days(7), "created_by_agent_or_user": "Emma Wilson", "review_status": "needs_revision"},
            {"id": "pv-004", "page_id": "page-004", "version_no": 1, "content_md": "Initial document pipeline draft.", "change_summary": "Initial draft", "created_at": days(3), "created_by_agent_or_user": "Carol Nguyen", "review_status": "needs_revision"},
            {"id": "pv-005", "page_id": "page-006", "version_no": 5, "content_md": "Current safety framework content.", "change_summary": "Clarified red-team step", "created_at": days(8), "created_by_agent_or_user": "Alice Chen", "review_status": "approved"},
        ],
        "page_claim_links": [
            {"id": "pcl-001", "page_id": "page-001", "claim_id": "clm-001", "section_key": "requirements", "citation_style": "inline"},
            {"id": "pcl-002", "page_id": "page-002", "claim_id": "clm-003", "section_key": "retrieval", "citation_style": "inline"},
            {"id": "pcl-003", "page_id": "page-003", "claim_id": "clm-005", "section_key": "updates", "citation_style": "footnote"},
            {"id": "pcl-004", "page_id": "page-004", "claim_id": "clm-004", "section_key": "qa", "citation_style": "inline"},
            {"id": "pcl-005", "page_id": "page-006", "claim_id": "clm-002", "section_key": "thresholds", "citation_style": "inline"},
        ],
        "page_links": [
            {"id": "pl-001", "from_page_id": "page-001", "to_page_id": "page-006", "relation_type": "related_to", "auto_generated": True},
            {"id": "pl-002", "from_page_id": "page-002", "to_page_id": "page-003", "relation_type": "related_to", "auto_generated": True},
            {"id": "pl-003", "from_page_id": "page-003", "to_page_id": "page-002", "relation_type": "depends_on", "auto_generated": True},
        ],
        "page_source_links": [
            {"id": "psl-001", "page_id": "page-001", "source_id": "src-001"},
            {"id": "psl-002", "page_id": "page-002", "source_id": "src-002"},
            {"id": "psl-003", "page_id": "page-003", "source_id": "src-002"},
            {"id": "psl-004", "page_id": "page-003", "source_id": "src-005"},
            {"id": "psl-005", "page_id": "page-004", "source_id": "src-003"},
            {"id": "psl-006", "page_id": "page-005", "source_id": "src-004"},
            {"id": "psl-007", "page_id": "page-006", "source_id": "src-001"},
        ],
        "jobs": [
            {"id": "job-001", "job_type": "ingest", "status": "completed", "started_at": hours(30), "finished_at": hours(29), "input_ref": "src-005", "output_ref": "chunks:src-005", "error_message": None, "logs_json": ["validated", "parsed", "indexed"]},
            {"id": "job-002", "job_type": "review", "status": "completed", "started_at": hours(22), "finished_at": hours(21), "input_ref": "page-006", "output_ref": "review:page-006", "error_message": None, "logs_json": ["review generated", "approved"]},
            {"id": "job-003", "job_type": "rebuild", "status": "failed", "started_at": hours(5), "finished_at": hours(5) + timedelta(minutes=12), "input_ref": "src-004", "output_ref": None, "error_message": "DOCX table parsing error", "logs_json": ["validation passed", "parser crashed on malformed table"]},
            {"id": "job-004", "job_type": "compose", "status": "failed", "started_at": hours(9), "finished_at": hours(8) + timedelta(minutes=35), "input_ref": "page-003", "output_ref": None, "error_message": "Review gate rejected unsupported claim", "logs_json": ["draft generated", "review failed"]},
        ],
        "review_items": [
            {"id": "rev-001", "page_id": "page-003", "page_title": "RAG Architecture", "page_slug": "rag-architecture", "page_status": "in_review", "issue_type": "unsupported_claim", "severity": "high", "old_content_md": "Older RAG content", "new_content_md": "New RAG content with HyDE section", "change_summary": "Added quarterly update references", "confidence_score": 0.81, "created_at": hours(10), "updated_at": hours(8), "assigned_to": "Alice Chen", "previous_version": 1, "source_ids": ["src-002", "src-005"], "evidence_snippets": [{"sourceId": "src-005", "sourceTitle": "Q1 2025 Knowledge Base Update", "chunkId": "chunk-008", "content": "Parent document retrieval reduces citation fragmentation by 34 percent.", "relevance": 0.88}]}
        ],
        "review_issues": [
            {"id": "ri-001", "review_item_id": "rev-001", "issue_type": "unsupported_claim", "severity": "high", "message": "The 34 percent improvement claim is not yet verified.", "evidence": "Claim clm-005 is still marked unverified.", "source_chunk_id": "chunk-008", "claim_id": "clm-005"}
        ],
    }
